version: '3.1'
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    links:
      - mysql:mysql
  mysql:
    image: mysql    
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root